theme = "onedark"

[editor]
scrolloff = 8
line-number = "relative"
mouse = false
gutters = ["diagnostics", "line-numbers", "spacer"]
bufferline = "multiple"
popup-border = "all"
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = false

[keys.normal]
g = { a = "code_action" } 
"ret" = ["open_below", "normal_mode"] 
"A-x" = "@x<A-d>" 

[keys.insert]
"A-x" = "normal_mode"
j = { k = "normal_mode" }
